### ISSUE TITLE
Is there a protocol spec anywhere?

### ISSUE THREAD

**Issue by anderspitman** [ngrok/muxado-go#3]
Interesting library. Also I noticed yamux in go.mod, but apparently it's only used in a test. A comparison to yamux would be very useful.

**Comment by anderspitman** [comment]
I managed to find this, which I'm guessing is the best thing available: https://github.com/ngrok/ngrok-rust/blob/main/muxado/PROTOCOL.md

**Comment by anderspitman** [comment]
For the second part of my question, this was useful: https://github.com/inconshreveable/muxado/issues/13

**Comment by euank** [comment]
Thanks for the question! 
The simple answer is "no, there's not a public official spec anywhere".
Basically, your understanding above seems accurate to me.

The implementation in this repository is, I believe, the closest there is to a spec.
Per the open source license in this repo, you're welcome to use this code for whatever purpose.

That said, I believe ngrok's position is that only clients using the official [Agent SDKs](https://ngrok.com/docs/agent-sdks/) or ngrok agent are supported, and anyone speaking muxado directly to ngrok's servers should expect no support, and possibly to be broken unexpectedly.

Since it's not supported to speak this protocol directly, outside of the ngrok-maintained implementations of it, I don't particularly expect a more official spec or such.

**Comment by anderspitman** [comment]
Thanks @euank, that all makes sense. I'm actually working on my own protocol, so not a huge deal if ngrok breaks compatibility in the future. I'm mostly just using muxado to save some time since it seems like a reasonable approach to stream muxing, and has production-quality implementations.
